#!/bin/bash

# Remove the styleguide from previous builds.
echo -n "Deleting previous styleguide..."
rm -rf public *.html
echo " done."

# Build the CSS with Bundler, Sass and Compass.
compass compile

# Build the styleguide using kss-node.
# kss-node [source files to parse] [destination folder] --template [location of template files]
kss-node ./sass styleguide  --template ./custom-template --css ./../css/ipfa_styles.css;
